### ISSUE TITLE
cannot use request.Reaction (variable of type []tg.ReactionClass) as type string in assignment

### ISSUE THREAD

**Issue by sarff** [anonyindian/gotgproto#21]
HI. 
Have "Compilation finished with exit code 2"
just tried running the example echo-bot
```
# github.com/anonyindian/gotgproto/ext
../../go/pkg/mod/github.com/anonyindian/gotgproto@v1.0.0-beta08/ext/context.go:174:14: cannot use request.Reaction (variable of type []tg.ReactionClass) as type string in assignment
```

**Comment by anonyindian** [comment]
Hello! It's a known issue with the mismatched versioning of the dependencies, you can fix it with a temporary solution. This has already been fixed in the beta branch, hence you can command go compiler force get the branch instead of the latest released version of the package. Refer to following issue, which covers the same context:
https://github.com/anonyindian/gotgproto/issues/20#issuecomment-1399250506

It shall fix the issue you're facing, sorry for the inconvenience!

**Comment by sarff** [comment]
working thx
